static_dir = "./static/"
log_dir = "/logs"
instance_name = "tts"
authorized_ids = ["public_token"]

[modules.tts_py]
type = "Py"
path = "/api/tts_streaming"
text_tokenizer_file = "hf://kyutai/unmute/test_en_fr_audio_8000.model"
batch_size = 16
text_bos_token = 1

[modules.tts_py.py]
log_folder = "/logs"
# We could use replace **/*.safetensors with unmute-prod-website/*.safetensors
# to only get the voices used in Unmute, but we are using the TTS for the demo
# on the project page too and for that we want to load the other voices as well
voice_folder = "hf-snapshot://kyutai/unmute-voices/**/*.safetensors"
default_voice = "unmute-prod-website/default_voice.wav"
cfg_coef = 2.0
n_q = 24
