static_dir = "./static/"
log_dir = "/logs"
instance_name = "tts"
authorized_ids = ["public_token"]

[modules.tts_py]
type = "Py"
path = "/api/tts_streaming"
script = "/app/moshi-server/tts.py"
text_tokenizer_file = "/models/test_en_fr_audio_8000.model"
batch_size = 16
text_bos_token = 1

[modules.tts_py.py]
log_folder = "/logs"
moshi_weight = "/models/tts_2961f6b6@82/checkpoint.safetensors"
config_path = "/models/tts_2961f6b6@82/config.json"
voice_folder = "/models/"
default_voice = "barack_demo.wav"
