static_dir = "./static/"
log_dir = "/logs"
instance_name = "tts"
authorized_ids = ["public_token"]

[modules.tts_py]
type = "Py"
path = "/api/tts_streaming"
text_tokenizer_file = "hf://kyutai/unmute/test_en_fr_audio_8000.model"
batch_size = 16
text_bos_token = 1

[modules.tts_py.py]
log_folder = "/logs"
moshi_weight = "hf://kyutai/unmute/tts_2961f6b6@82_checkpoint.safetensors"
config_path = "hf://kyutai/unmute/tts_2961f6b6@82_config.json"
voice_folder = "hf-snapshot://kyutai/unmute-voices"
default_voice = "barack_demo.wav"
