static_dir = "./static/"
log_dir = "$HOME/tmp/tts-logs"
instance_name = "voice"
authorized_ids = ["public_token"]

[modules.voice_py]
type = "PyPost"
path = "/api/voice"
# This is the only way currently to get the python file.
script = "/app/moshi-server/voice.py"

[modules.voice_py.py]
mimi_weight = "/models/e9d43d50_500_mimi_voice.safetensors"
